version: "3.4"

services:
  proxy:
    image: docker/proxy
    build: ./gatsby-app
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./gatsby-app/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: curl -f localhost/ & curl -f localhost/api/ping || exit 1
      interval: 90s
      timeout: 10s
      retries: 5
    depends_on:
      - api
    networks:
      - front
      - back
  api:
    image: docker/backend
    build: ./api
    container_name: api
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET="To be, or not to be, that is the question"
      - BASE_URL=localhost:4000
    healthcheck:
      test: curl localhost:4000/api/ping
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - db
    networks:
      - back

  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 50s
    networks:
      - back
networks:
  front:
    driver: bridge
  back:
    driver: bridge